import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { openDatabase } from '../db/database.js';
import { runDibaQualityAudit } from './dibaQualityAudit.js';
import { APPROVED_POSSIBLE_LINKS, approvedPossibleSourceKeys } from './dibaHumanReviewedPossible.js';
import { identityKey } from './dibaPolicyOverrides.js';
import { loadPolicyIdentityIndex, planDibaPolicy } from './dibaPolicyPlanner.js';

export const E4_CONFIRMATION = 'M1.4E4_REAL_LOCAL_POSSIBLE_LINK_APPLY';
export const E4_BASELINE_SHA = '7F105EA451E8E86EBE4D1386A102F7D73542991CAA6A42F09C6A6D79B1D17337';
const DIBA_KEYS = ['diba-tourisme', 'diba-escenari', 'diba-museus'];

function comparable(value) { return process.platform === 'win32' ? path.resolve(value).toLowerCase() : path.resolve(value); }
function stable(value) { return { sourceKey: value.sourceKey, sourceRecordId: String(value.sourceRecordId) }; }
function sha256File(filePath) { return createHash('sha256').update(fs.readFileSync(filePath)).digest('hex').toUpperCase(); }
function remaining(policy) { return { confirmed: policy.crossSource.confirmed.filter(({ activationBlocker }) => activationBlocker).length, possible: policy.crossSource.possible.filter(({ activationBlocker }) => activationBlocker).length, sameFeed: policy.sameFeed.filter(({ decision }) => decision === 'NEEDS_HUMAN_REVIEW').length, sessionDefer: policy.sameFeed.filter(({ decision }) => decision === 'KEEP_SEPARATE_SESSION').length, activationReady: policy.activation.publicActivationReady }; }
function sourceStates(db) { return db.prepare(`SELECT key, enabled, allows_images FROM sources WHERE key IN (${DIBA_KEYS.map(() => '?').join(',')}) ORDER BY key`).all(...DIBA_KEYS); }
function logicalCounts(db) { return { plans: db.prepare('SELECT COUNT(*) AS count FROM plans').get().count, planSources: db.prepare('SELECT COUNT(*) AS count FROM plan_sources').get().count, categories: db.prepare('SELECT COUNT(*) AS count FROM plan_categories').get().count, occurrences: db.prepare('SELECT COUNT(*) AS count FROM plan_occurrences').get().count, sources: db.prepare('SELECT COUNT(*) AS count FROM sources').get().count, dibaSourceRecords: db.prepare("SELECT COUNT(*) AS count FROM plan_sources ps JOIN sources s ON s.id=ps.source_id WHERE s.key LIKE 'diba-%'").get().count, duplicateStableIdentities: db.prepare('SELECT COUNT(*) AS count FROM (SELECT source_id, source_record_id FROM plan_sources GROUP BY source_id, source_record_id HAVING COUNT(*) > 1)').get().count }; }
function sourcePayload(db, identity) { const row = db.prepare('SELECT ps.source_payload_json AS payload FROM plan_sources ps JOIN sources s ON s.id=ps.source_id WHERE s.key=? AND ps.source_record_id=?').get(identity.sourceKey, identity.sourceRecordId); return JSON.parse(row?.payload || '{}'); }
async function policyAt(databasePath, overrides) { const auditReport = await runDibaQualityAudit({ databasePath }); const db = openDatabase(databasePath, { readonly: true }); try { const identityIndex = loadPolicyIdentityIndex(db); return { auditReport, identityIndex, policy: planDibaPolicy({ auditReport, overrides, identityIndex }) }; } finally { db.close(); } }
function geographyPreview(db, operations) { const plan = db.prepare('SELECT municipality, comarca FROM plans WHERE id=?'); return operations.map((operation) => { const target = plan.get(operation.diagnostic.expectedCurrentTargetPlanId); if (!target) throw new Error('E4 geography target disappeared during preflight.'); const mutation = operation.geography.resolutionType === 'COMARCA_ONLY' ? !target.municipality && !target.comarca : !target.municipality; return { source: stable(operation.source), finalTargetAnchor: stable(operation.finalTargetAnchor), outcome: mutation ? 'MUTATION_PROPOSED' : 'NOOP_EXISTING_GEOGRAPHY' }; }); }

export function canonicalE4PrimaryLocalPath(config) { return path.resolve(config.projectRoot, 'data', 'quefem.sqlite'); }
export function assertE4AuthorizationArguments({ databasePath, expectedSha, confirmation }, config) { const primary = canonicalE4PrimaryLocalPath(config); if (databasePath && comparable(databasePath) !== comparable(primary)) throw new Error('E4 authorizes only this repository canonical data/quefem.sqlite path.'); if (comparable(config.databasePath) !== comparable(primary)) throw new Error('E4 configuration does not point to the canonical primary database path.'); if (confirmation !== E4_CONFIRMATION) throw new Error('E4 confirmation token is missing or invalid.'); if (!/^[A-Fa-f0-9]{64}$/.test(expectedSha || '') || expectedSha.toUpperCase() !== E4_BASELINE_SHA) throw new Error('E4 expected SHA must equal the one-time approved E4 baseline.'); return primary; }
export function assertE4BackupPath(backupPath, config) { const directory = path.resolve(config.projectRoot, 'data', 'backups'); const resolved = path.resolve(backupPath); if (path.relative(directory, resolved).startsWith('..') || path.relative(directory, resolved) === '') throw new Error('E4 backup must be a new file below data/backups.'); return resolved; }
export function assertE4WritableBaseline({ databasePath, args, config }) { const primary = assertE4AuthorizationArguments(args, config); if (comparable(databasePath) !== comparable(primary)) throw new Error('E4 writable boundary received a non-canonical primary database path.'); const actualSha = sha256File(primary); if (actualSha !== E4_BASELINE_SHA || actualSha !== args.expectedSha.toUpperCase()) throw new Error(`E4 expected SHA does not match current primary database at writable boundary: ${actualSha}`); return { primary, sha256: actualSha }; }
export function readonlyE4State(databasePath) { const db = openDatabase(databasePath, { readonly: true }); try { const integrity = db.pragma('integrity_check', { simple: true }); const sources = sourceStates(db); const counts = logicalCounts(db); if (integrity !== 'ok') throw new Error(`E4 integrity_check failed: ${integrity}`); if (sources.length !== 3 || sources.some(({ enabled, allows_images: images }) => Number(enabled) !== 0 || Number(images) !== 0)) throw new Error('E4 requires DIBA sources disabled and images disabled.'); if (counts.duplicateStableIdentities) throw new Error('E4 requires unique stable source identities.'); return { integrity, sources, counts }; } finally { db.close(); } }

export function validateE4PolicyScope({ auditReport, identityIndex, policy, overrides, databasePath }) {
  if (!Array.isArray(overrides.decisions) || overrides.decisions.length !== 34) throw new Error('E4 requires exactly 34 approved human decisions.');
  const confirmed = overrides.decisions.filter(({ reviewedAt }) => reviewedAt === '2026-09-02'); const possibleDecisions = overrides.decisions.filter(({ reviewedAt }) => reviewedAt === '2026-09-03'); const approvedKeys = approvedPossibleSourceKeys();
  if (confirmed.length !== 11 || possibleDecisions.length !== 23 || possibleDecisions.some(({ source, decision }) => decision !== 'LINK_TO_EXISTING' || !approvedKeys.has(identityKey(source)))) throw new Error('E4 override state is not exactly 11 CONFIRMED plus 23 approved POSSIBLE decisions.');
  const mappings = policy.mutationPlan.phases.finalSourceMappings; const mappingKeys = new Set(mappings.map(({ source }) => identityKey(source))); const unexpected = mappings.filter(({ source }) => !approvedKeys.has(identityKey(source)));
  if (mappings.length !== 23 || unexpected.length || [...approvedKeys].some((key) => !mappingKeys.has(key))) throw new Error(`E4 planner scope differs from the 23 approved POSSIBLE mappings: ${mappings.length} mappings, ${unexpected.length} unexpected.`);
  const unresolved = remaining(policy); if (unresolved.confirmed || unresolved.possible || unresolved.sameFeed !== 4 || unresolved.sessionDefer !== 2 || unresolved.activationReady) throw new Error(`E4 pre-apply blockers differ: ${JSON.stringify(unresolved)}.`);
  const reviewedPossible = policy.crossSource.possible.filter(({ reviewedDecision }) => reviewedDecision === 'LINK_TO_EXISTING'); if (reviewedPossible.length !== 22 || policy.crossSource.possible.some(({ activationBlocker }) => activationBlocker)) throw new Error('E4 requires all 22 POSSIBLE components reviewed and non-blocking.');
  const validations = possibleDecisions.map((decision) => { const sourceEntries = identityIndex.byIdentity.get(identityKey(decision.source)) || []; const targetEntries = identityIndex.byIdentity.get(identityKey(decision.target)) || []; if (sourceEntries.length !== 1 || targetEntries.length !== 1) throw new Error(`E4 stable identity must resolve exactly once: ${identityKey(decision.source)}.`); const source = sourceEntries[0]; const target = targetEntries[0]; const mapping = mappings.find(({ source: item }) => identityKey(item) === identityKey(decision.source)); const component = reviewedPossible.find(({ component: item }) => item.dibaPlanIds.includes(source.planId) && item.candidatePlanIds.includes(target.planId)); if (!source.sourceKey.startsWith('diba-') || Number(source.enabled) !== 0 || target.sourceKey.startsWith('diba-') || Number(target.enabled) !== 1 || !mapping || !component || identityKey(mapping.finalTargetAnchor) !== identityKey(decision.target) || mapping.diagnostic.currentSourcePlanId !== source.planId || mapping.diagnostic.expectedCurrentTargetPlanId !== target.planId) throw new Error(`E4 source/target topology differs for ${identityKey(decision.source)}.`); return { source: stable(decision.source), target: stable(decision.target), sourcePlanId: source.planId, targetPlanId: target.planId, componentId: component.component.componentId, status: 'PASS' }; });
  const confirmedValidations = confirmed.map((decision) => { const source = (identityIndex.byIdentity.get(identityKey(decision.source)) || []); const target = (identityIndex.byIdentity.get(identityKey(decision.target)) || []); if (source.length !== 1 || target.length !== 1 || source[0].planId !== target[0].planId || mappings.some(({ source: item }) => identityKey(item) === identityKey(decision.source))) throw new Error(`E4 prior CONFIRMED decision is not already satisfied: ${identityKey(decision.source)}.`); return { source: stable(decision.source), target: stable(decision.target), planId: source[0].planId }; });
  const origins = policy.mutationPlan.phases.recomputeOrphans.originalAffectedDibaStagingPlans; if (origins.length !== 23 || new Set(origins.map(({ diagnostic }) => diagnostic.originalDibaStagingPlanId)).size !== 23) throw new Error('E4 requires 23 distinct POSSIBLE staging origins.');
  const bubbleSources = APPROVED_POSSIBLE_LINKS.filter(({ source }) => source.sourceRecordId.startsWith('escenari11243006859141174619136456')); const bubble = validations.filter(({ source }) => bubbleSources.some((item) => identityKey(item.source) === identityKey(source))); const db = openDatabase(databasePath, { readonly: true }); try { const schedule = db.prepare('SELECT schedule_text FROM plans WHERE id=?').get(bubble[0]?.targetPlanId)?.schedule_text || ''; const starts = bubbleSources.map(({ source }) => sourcePayload(db, source).data_inici || null); if (bubble.length !== 2 || new Set(bubble.map(({ componentId }) => componentId)).size !== 1 || new Set(bubble.map(({ target }) => identityKey(target))).size !== 1 || !starts.includes('2026-09-26 11:45:00') || !starts.includes('2026-09-26 18:00:00') || !/11\.45.*18/i.test(schedule)) throw new Error('E4 BubbleBike 2->1 precondition or combined schedule failed.'); return { mappings, validations, confirmedValidations, targetPlanIds: [...new Set(validations.map(({ targetPlanId }) => targetPlanId))], origins, unresolved, reviewedPossible: reviewedPossible.length, unexpected, bubbleBike: { sources: bubbleSources.map(({ source }) => stable(source)), target: bubble[0].target, componentId: bubble[0].componentId, canonicalSchedule: schedule, sessionStarts: starts } }; } finally { db.close(); }
}
export async function prepareE4ExecutionPlan(databasePath, overrides) { const prepared = await policyAt(databasePath, overrides); const scope = validateE4PolicyScope({ ...prepared, overrides, databasePath }); const db = openDatabase(databasePath, { readonly: true }); try { const geography = geographyPreview(db, prepared.policy.mutationPlan.phases.explicitGeography); if (geography.length !== 19 || geography.some(({ outcome }) => outcome !== 'NOOP_EXISTING_GEOGRAPHY')) throw new Error('E4 would apply unauthorized geography mutation.'); return { ...prepared, scope: { ...scope, geography } }; } finally { db.close(); } }
export async function preflightE4PrimaryLocal({ args, config, overrides }) { const { primary, sha256 } = assertE4WritableBaseline({ databasePath: canonicalE4PrimaryLocalPath(config), args, config }); return { primary, sha256, state: readonlyE4State(primary), prepared: await prepareE4ExecutionPlan(primary, overrides) }; }
export async function createVerifiedE4Backup(primary, backupPath, config, args) { const resolved = assertE4BackupPath(backupPath, config); if (fs.existsSync(resolved)) throw new Error(`E4 backup already exists: ${resolved}`); assertE4WritableBaseline({ databasePath: primary, args, config }); const before = readonlyE4State(primary); fs.mkdirSync(path.dirname(resolved), { recursive: true }); const source = openDatabase(primary, { readonly: true }); try { await source.backup(resolved); } finally { source.close(); } assertE4WritableBaseline({ databasePath: primary, args, config }); const backup = readonlyE4State(resolved); if (JSON.stringify(before.counts) !== JSON.stringify(backup.counts) || JSON.stringify(before.sources) !== JSON.stringify(backup.sources)) throw new Error('E4 verified backup is not logically equivalent to the pre-apply database.'); return { path: resolved, sha256: sha256File(resolved), integrity: backup.integrity, logicalEquivalent: true, counts: backup.counts, sourceStates: backup.sources }; }
