import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import 'dotenv/config';
import { loadConfig } from '../backend/src/config.js';
import { openDatabase } from '../backend/src/db/database.js';
import { runDibaQualityAudit } from '../backend/src/diba/dibaQualityAudit.js';
import { applyDibaPolicyRehearsal, cloneDibaRehearsal, sha256File, verifyDibaRepeatPreservation } from '../backend/src/diba/dibaPolicyExecutor.js';
import { APPROVED_POSSIBLE_LINKS, approvedPossibleSourceKeys } from '../backend/src/diba/dibaHumanReviewedPossible.js';
import { identityKey, loadDibaPolicyOverrides } from '../backend/src/diba/dibaPolicyOverrides.js';
import { loadPolicyIdentityIndex, planDibaPolicy } from '../backend/src/diba/dibaPolicyPlanner.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const overridePath = path.join(root, 'data-policy', 'diba-link-overrides.json');
const expectedRealSha = '7F105EA451E8E86EBE4D1386A102F7D73542991CAA6A42F09C6A6D79B1D17337';
const protectedFields = ['original_title', 'original_description', 'start_date', 'end_date', 'schedule_text', 'venue_name', 'address', 'latitude', 'longitude', 'website_url', 'image_url', 'ticket_url', 'status', 'inactive_at', 'featured', 'quality_score'];
function stable(value) { return { sourceKey: value.sourceKey, sourceRecordId: String(value.sourceRecordId) }; }
function key(value) { return identityKey(value); }
function equal(left, right) { return JSON.stringify(left) === JSON.stringify(right); }
function timestampedTarget() { return path.join(root, 'data', 'rehearsal', `quefem_diba_m1_4e3_possible_${new Date().toISOString().replace(/[:.]/g, '-')}.sqlite`); }
function remaining(policy) { return { confirmed: policy.crossSource.confirmed.filter(({ activationBlocker }) => activationBlocker).length, possible: policy.crossSource.possible.filter(({ activationBlocker }) => activationBlocker).length, sameFeed: policy.sameFeed.filter(({ decision }) => decision === 'NEEDS_HUMAN_REVIEW').length, sessionDefer: policy.sameFeed.filter(({ decision }) => decision === 'KEEP_SEPARATE_SESSION').length, activationReady: policy.activation.publicActivationReady }; }
function assertRealHash(config, stage) { const hash = sha256File(config.databasePath); if (hash !== expectedRealSha) throw new Error(`E3 real DB SHA changed or is unexpected at ${stage}: ${hash}`); return hash; }
function countRows(db) { return db.prepare('SELECT COUNT(*) AS count FROM plan_sources').get().count; }
function logicalCounts(db) { return { plans: db.prepare('SELECT COUNT(*) AS count FROM plans').get().count, planSources: countRows(db), categories: db.prepare('SELECT COUNT(*) AS count FROM plan_categories').get().count, occurrences: db.prepare('SELECT COUNT(*) AS count FROM plan_occurrences').get().count, sources: db.prepare('SELECT COUNT(*) AS count FROM sources').get().count, dibaSourceRecords: db.prepare("SELECT COUNT(*) AS count FROM plan_sources ps JOIN sources s ON s.id=ps.source_id WHERE s.key LIKE 'diba-%'").get().count, duplicateStableIdentities: db.prepare('SELECT COUNT(*) AS count FROM (SELECT source_id, source_record_id FROM plan_sources GROUP BY source_id, source_record_id HAVING COUNT(*) > 1)').get().count }; }
function targetSnapshot(db, planIds) { const plan = db.prepare('SELECT * FROM plans WHERE id=?'); const categories = db.prepare('SELECT category_id FROM plan_categories WHERE plan_id=? ORDER BY category_id'); return Object.fromEntries(planIds.map((id) => [id, { fields: Object.fromEntries(protectedFields.map((field) => [field, plan.get(id)?.[field]])), categories: categories.all(id).map(({ category_id: categoryId }) => categoryId) }])); }
function diffSnapshots(before, after) { const differences = []; for (const [planId, left] of Object.entries(before)) { const right = after[planId]; for (const field of protectedFields) if (left.fields[field] !== right.fields[field]) differences.push({ planId: Number(planId), field, before: left.fields[field], after: right.fields[field] }); if (!equal(left.categories, right.categories)) differences.push({ planId: Number(planId), field: 'categories', before: left.categories, after: right.categories }); } return differences; }
function sourcePlans(db, identities) { const find = db.prepare('SELECT ps.plan_id AS planId FROM plan_sources ps JOIN sources s ON s.id=ps.source_id WHERE s.key=? AND ps.source_record_id=?'); return Object.fromEntries(identities.map((value) => [key(value), find.all(value.sourceKey, value.sourceRecordId).map(({ planId }) => planId)])); }
function geographyPreview(db, operations) { const plan = db.prepare('SELECT municipality, comarca FROM plans WHERE id=?'); return operations.map((operation) => { const target = plan.get(operation.diagnostic.expectedCurrentTargetPlanId); if (!target) throw new Error('E3 geography target disappeared during preflight.'); const mutate = operation.geography.resolutionType === 'COMARCA_ONLY' ? !target.municipality && !target.comarca : !target.municipality; return { source: stable(operation.source), outcome: mutate ? 'MUTATION_PROPOSED' : 'NOOP_EXISTING_GEOGRAPHY' }; }); }
function integrityAt(databasePath) { const db = openDatabase(databasePath, { readonly: true }); try { return db.pragma('integrity_check', { simple: true }); } finally { db.close(); } }
async function policyState(databasePath, overrides) { const audit = await runDibaQualityAudit({ databasePath }); const db = openDatabase(databasePath, { readonly: true }); try { const index = loadPolicyIdentityIndex(db); return { audit, index, policy: planDibaPolicy({ auditReport: audit, overrides, identityIndex: index }) }; } finally { db.close(); } }
function componentMembers(item) { return item.cluster.records.map(({ sourceKey, sourceRecordId }) => `${sourceKey || item.cluster.sourceKey}:${sourceRecordId}`).sort(); }
function componentSignature(item) { return componentMembers(item).join('|'); }
function blockerComponents(state, decision) { return state.policy.sameFeed.filter((item) => item.decision === decision).map((item) => ({ signature: componentSignature(item), members: componentMembers(item), planIds: [...(item.planIds || item.cluster.planIds)].sort((left, right) => left - right), reasons: item.reasons })); }

export function validateExpectedSameFeedTransition({ preState, postState, bubbleSources }) {
  const preSameFeed = blockerComponents(preState, 'NEEDS_HUMAN_REVIEW'); const postSameFeed = blockerComponents(postState, 'NEEDS_HUMAN_REVIEW'); const preSessionDefer = blockerComponents(preState, 'KEEP_SEPARATE_SESSION'); const postSessionDefer = blockerComponents(postState, 'KEEP_SEPARATE_SESSION');
  const bubbleSignature = [...bubbleSources].map(key).sort().join('|'); const preKeys = new Set(preSameFeed.map(({ signature }) => signature)); const postKeys = new Set(postSameFeed.map(({ signature }) => signature)); const removed = preSameFeed.filter(({ signature }) => !postKeys.has(signature)); const added = postSameFeed.filter(({ signature }) => !preKeys.has(signature));
  if (!preKeys.has(bubbleSignature) || removed.length !== 1 || removed[0].signature !== bubbleSignature || added.length || postSameFeed.some(({ signature }) => signature === bubbleSignature)) throw new Error('E3 same-feed transition is not exactly the approved BubbleBike component removal.');
  if (!equal(preSessionDefer.map(({ signature }) => signature).sort(), postSessionDefer.map(({ signature }) => signature).sort())) throw new Error('E3 session-DEFER component identities changed unexpectedly.');
  const bubblePostCluster = postState.audit.sameFeed.clusters.find((cluster) => cluster.records.map(({ sourceKey = cluster.sourceKey, sourceRecordId }) => `${sourceKey}:${sourceRecordId}`).sort().join('|') === bubbleSignature);
  if (!bubblePostCluster || new Set(bubblePostCluster.planIds).size !== 1) throw new Error('E3 BubbleBike did not become one same-plan component after the approved two-to-one relinks.');
  return { preSameFeed, postSameFeed, removed, added, preSessionDefer, postSessionDefer, bubblePostCluster: { members: bubblePostCluster.records.map(({ sourceKey = bubblePostCluster.sourceKey, sourceRecordId }) => `${sourceKey}:${sourceRecordId}`).sort(), planIds: bubblePostCluster.planIds, classification: bubblePostCluster.classification } };
}

export function validateE3PreApply(state, overrides, db) {
  if (overrides.decisions.length !== 34) throw new Error(`E3 requires exactly 34 overrides; found ${overrides.decisions.length}.`);
  const previous = overrides.decisions.filter(({ reviewedAt }) => reviewedAt === '2026-09-02'); const approved = overrides.decisions.filter(({ reviewedAt }) => reviewedAt === '2026-09-03');
  if (previous.length !== 11 || approved.length !== 23 || approved.some(({ source }) => !approvedPossibleSourceKeys().has(key(source)))) throw new Error('E3 override state does not contain 11 historical CONFIRMED plus 23 approved POSSIBLE decisions.');
  const mappings = state.policy.mutationPlan.phases.finalSourceMappings; const pendingKeys = new Set(mappings.map(({ source }) => key(source))); const approvedKeys = approvedPossibleSourceKeys();
  if (mappings.length !== 23 || [...pendingKeys].some((item) => !approvedKeys.has(item)) || [...approvedKeys].some((item) => !pendingKeys.has(item))) throw new Error('E3 pending planner mappings are not exactly the 23 approved POSSIBLE source identities.');
  const automaticMappings = mappings.filter(({ diagnostic }) => diagnostic.policy !== 'DIRECT_OR_COMPOSED_PUBLIC_LINK'); if (automaticMappings.length) throw new Error('E3 found unexpected automatic mapping(s).');
  const possible = state.policy.crossSource.possible; if (possible.length !== 22 || possible.filter(({ reviewedDecision }) => reviewedDecision === 'LINK_TO_EXISTING').length !== 22 || possible.some(({ activationBlocker }) => activationBlocker)) throw new Error('E3 POSSIBLE review state is incomplete.');
  const unresolved = remaining(state.policy); if (unresolved.confirmed || unresolved.possible || unresolved.sameFeed !== 4 || unresolved.sessionDefer !== 2 || unresolved.activationReady) throw new Error(`E3 pre-apply blocker state differs: ${JSON.stringify(unresolved)}.`);
  const geography = geographyPreview(db, state.policy.mutationPlan.phases.explicitGeography); if (geography.length !== 19 || geography.some(({ outcome }) => outcome !== 'NOOP_EXISTING_GEOGRAPHY')) throw new Error('E3 geography preflight is not exactly 0 mutations / 19 NOOP.');
  const validations = approved.map((decision) => { const sourceEntries = state.index.byIdentity.get(key(decision.source)) || []; const targetEntries = state.index.byIdentity.get(key(decision.target)) || []; if (sourceEntries.length !== 1 || targetEntries.length !== 1) throw new Error(`E3 stable identity does not resolve exactly once for ${key(decision.source)}.`); const source = sourceEntries[0]; const target = targetEntries[0]; const component = possible.find(({ component: item }) => item.dibaPlanIds.includes(source.planId) && item.candidatePlanIds.includes(target.planId)); const mapping = mappings.find((item) => key(item.source) === key(decision.source)); if (!source.sourceKey.startsWith('diba-') || source.enabled !== 0 || target.sourceKey.startsWith('diba-') || target.enabled !== 1 || !component || !mapping || key(mapping.finalTargetAnchor) !== key(decision.target)) throw new Error(`E3 source/target topology or approved target differs for ${key(decision.source)}.`); return { source: stable(decision.source), target: stable(decision.target), sourcePlanId: source.planId, targetPlanId: target.planId, componentId: component.component.componentId, status: 'PASS' }; });
  const confirmedPlans = sourcePlans(db, previous.map(({ source }) => source)); for (const decision of previous) { const source = state.index.byIdentity.get(key(decision.source))[0]; const target = state.index.byIdentity.get(key(decision.target))[0]; if (!equal(confirmedPlans[key(decision.source)], [target.planId]) || mappings.some(({ source: item }) => key(item) === key(decision.source)) || source.planId !== target.planId) throw new Error(`E3 historical CONFIRMED override is not already satisfied: ${key(decision.source)}.`); }
  const bubble = APPROVED_POSSIBLE_LINKS.filter(({ source }) => source.sourceRecordId.startsWith('escenari11243006859141174619136456')); const bubbleValidation = validations.filter(({ source }) => bubble.some((item) => key(item.source) === key(source))); const schedule = db.prepare('SELECT schedule_text FROM plans WHERE id=?').get(bubbleValidation[0]?.targetPlanId)?.schedule_text || null; const payload = db.prepare('SELECT ps.source_payload_json AS payload FROM plan_sources ps JOIN sources s ON s.id=ps.source_id WHERE s.key=? AND ps.source_record_id=?'); const starts = bubble.map(({ source }) => JSON.parse(payload.get(source.sourceKey, source.sourceRecordId)?.payload || '{}').data_inici || null);
  if (bubbleValidation.length !== 2 || new Set(bubbleValidation.map(({ componentId }) => componentId)).size !== 1 || new Set(bubbleValidation.map(({ target }) => key(target))).size !== 1 || !starts.includes('2026-09-26 11:45:00') || !starts.includes('2026-09-26 18:00:00') || !/11\.45.*18/i.test(schedule || '')) throw new Error('E3 BubbleBike component/session precondition failed.');
  return { previous, approved, mappings, validations, targetPlanIds: [...new Set(validations.map(({ targetPlanId }) => targetPlanId))], geography, unresolved, bubbleBike: { sources: bubble.map(({ source }) => source), target: bubbleValidation[0].target, componentId: bubbleValidation[0].componentId, sessionStarts: starts, canonicalSchedule: schedule } };
}

function render(output) { return `# DIBA M1.4E3 — Human-reviewed POSSIBLE links rehearsal\n\n**REHEARSAL DATABASE ONLY — REAL LOCAL DATABASE NOT MUTATED.**\n\n- Rehearsal: \`${output.rehearsalPath}\`\n- Real SHA checkpoints: ${Object.entries(output.realHashes).map(([stage, hash]) => `${stage}=\`${hash}\``).join('; ')}\n- Overrides: ${output.preApply.overrideCount}; historical CONFIRMED already satisfied: ${output.preApply.alreadySatisfiedConfirmed}\n- First apply: ${output.first.finalRelinks.length} relinks; unexpected ${output.first.unexpectedRelinks.length}; missing ${output.first.missingRelinks.length}\n- plan_sources: ${output.first.planSources.before} -> ${output.first.planSources.after}\n- Components: 21 x 1->1 and BubbleBike 2->1; public targets ${output.first.distinctPublicTargets}\n- Orphans: origins ${output.first.distinctOriginPlans}; zero-provenance ${output.first.recomputedOrphans.length}; inactivated ${output.first.inactivatedOrphans.length}\n- Public protected diffs: ${output.publicProtection.differences.length}; BubbleBike canonical schedule: ${output.bubbleBike.canonicalSchedule}\n- Geography: ${output.first.geography.mutations} mutations / ${output.first.geography.noops} NOOP\n- Repeat preservation: POSSIBLE ${output.repeat.possible.verified.length}/23; CONFIRMED ${output.repeat.confirmed.verified.length}/11\n- Second apply: ${output.second.finalRelinks.length} relinks; ${output.second.inactivatedOrphans.length} orphans; geography ${output.second.geography.mutations}/${output.second.geography.noops}\n- Blockers: CONFIRMED ${output.blockers.confirmed}; POSSIBLE ${output.blockers.possible}; same-feed ${output.blockers.sameFeed}; session DEFER ${output.blockers.sessionDefer}; activation ready=${output.blockers.activationReady}\n- Integrity: ${output.databaseInvariants.post.integrity}\n`; }

function renderComponentList(components) {
  return components.length ? components.map(({ members, planIds }) => `- ${members.join(', ')} (plans: ${planIds.join(', ')})`).join('\n') : '- none';
}

function renderSameFeedTransition(output) {
  const transition = output.sameFeedTransition;
  return `\n## SAME-FEED TRANSITION\n\nPRE same-feed multi-plan components:\n${renderComponentList(transition.preSameFeed)}\n\nRemoved component:\n${renderComponentList(transition.removed)}\n\nReason removed: BubbleBike same-feed blocker resolved as a direct expected consequence of the approved human 2->1 cross-source consolidation. This is not an automatic same-feed decision. Both DIBA source rows now resolve to plan ${transition.bubblePostCluster.planIds.join(', ')}.\n\nPOST same-feed multi-plan components:\n${renderComponentList(transition.postSameFeed)}\n\nAdded components:\n${renderComponentList(transition.added)}\n\nSession-DEFER identity preservation (PRE):\n${renderComponentList(transition.preSessionDefer)}\n\nSession-DEFER identity preservation (POST):\n${renderComponentList(transition.postSessionDefer)}\n`;
}

export async function main(config = loadConfig(), { rehearsalPath = timestampedTarget() } = {}) {
  const realBefore = assertRealHash(config, 'before copy'); const overrides = await loadDibaPolicyOverrides(overridePath); const target = path.resolve(rehearsalPath); const copy = await cloneDibaRehearsal(config.databasePath, target); const rehearsalPreSha = sha256File(target);
  const rehearsalState = await policyState(target, overrides); const preDb = openDatabase(target, { readonly: true }); let pre; let beforeSources; let beforeTargets; let preCounts; let previousConfirmedPlans;
  try { pre = validateE3PreApply(rehearsalState, overrides, preDb); beforeSources = countRows(preDb); beforeTargets = targetSnapshot(preDb, pre.targetPlanIds); preCounts = logicalCounts(preDb); previousConfirmedPlans = sourcePlans(preDb, pre.previous.map(({ source }) => source)); } finally { preDb.close(); }
  const firstApply = await applyDibaPolicyRehearsal({ databasePath: target, realDatabasePath: config.databasePath, overrides }); const realAfterFirst = assertRealHash(config, 'after first apply'); const approvedKeys = approvedPossibleSourceKeys(); const relinkKeys = new Set(firstApply.finalRelinks.map(({ source }) => key(source))); const unexpectedRelinks = firstApply.finalRelinks.filter(({ source }) => !approvedKeys.has(key(source))); const missingRelinks = [...approvedKeys].filter((item) => !relinkKeys.has(item));
  if (firstApply.finalRelinks.length !== 23 || unexpectedRelinks.length || missingRelinks.length || relinkKeys.size !== 23) throw new Error(`E3 first-apply relink scope failed: ${firstApply.finalRelinks.length} relinks, ${unexpectedRelinks.length} unexpected, ${missingRelinks.length} missing.`);
  const firstDb = openDatabase(target, { readonly: true }); let afterSources; let afterTargets; let postCounts; let orphanChecks; let confirmedChanged;
  try { afterSources = countRows(firstDb); afterTargets = targetSnapshot(firstDb, pre.targetPlanIds); postCounts = logicalCounts(firstDb); orphanChecks = firstApply.inactivatedOrphans.map(({ planId }) => ({ planId, remainingPlanSources: firstDb.prepare('SELECT COUNT(*) AS count FROM plan_sources WHERE plan_id=?').get(planId).count, status: firstDb.prepare('SELECT status FROM plans WHERE id=?').get(planId).status })); const afterConfirmed = sourcePlans(firstDb, pre.previous.map(({ source }) => source)); confirmedChanged = Object.keys(previousConfirmedPlans).filter((item) => !equal(previousConfirmedPlans[item], afterConfirmed[item])); } finally { firstDb.close(); }
  if (beforeSources !== afterSources || !equal(preCounts, postCounts) || orphanChecks.some(({ remainingPlanSources, status }) => remainingPlanSources !== 0 || status !== 'inactive') || confirmedChanged.length) throw new Error('E3 first-apply structural or historical CONFIRMED invariant failed.'); const differences = diffSnapshots(beforeTargets, afterTargets); if (differences.length) throw new Error(`E3 changed ${differences.length} protected public canonical field(s).`);
  const geographyFirst = { mutations: firstApply.geography.filter(({ outcome }) => outcome === 'MUTATED_APPROVED_GEOGRAPHY').length, noops: firstApply.geography.filter(({ outcome }) => outcome === 'NOOP_EXISTING_GEOGRAPHY').length }; if (geographyFirst.mutations || geographyFirst.noops !== 19) throw new Error('E3 first-apply geography result is not 0 mutations / 19 NOOP.');
  const bubbleTargetPlan = pre.validations.find(({ source }) => source.sourceRecordId === 'escenari112430068591411746191364560').targetPlanId; const bubbleAfter = openDatabase(target, { readonly: true }); let bubbleSchedule; try { bubbleSchedule = bubbleAfter.prepare('SELECT schedule_text FROM plans WHERE id=?').get(bubbleTargetPlan).schedule_text; } finally { bubbleAfter.close(); } if (bubbleSchedule !== pre.bubbleBike.canonicalSchedule) throw new Error('E3 BubbleBike combined canonical schedule changed.');
  const repeatPossible = verifyDibaRepeatPreservation({ databasePath: target, relinks: firstApply.finalRelinks }); const confirmedRelinks = pre.previous.map(({ source, target }) => ({ source, afterPlanId: pre.validations.find(({ source: item }) => key(item) === key(source))?.targetPlanId || rehearsalState.index.byIdentity.get(key(target))[0].planId })); const repeatConfirmed = verifyDibaRepeatPreservation({ databasePath: target, relinks: confirmedRelinks }); const realAfterRepeat = assertRealHash(config, 'after repeat preservation'); if (repeatPossible.verified.length !== 23 || repeatConfirmed.verified.length !== 11) throw new Error('E3 repeat preservation did not retain all 34 reviewed sources.');
  const postState = await policyState(target, overrides); const blockers = remaining(postState.policy); const sameFeedTransition = validateExpectedSameFeedTransition({ preState: rehearsalState, postState, bubbleSources: pre.bubbleBike.sources }); if (blockers.confirmed || blockers.possible || blockers.sessionDefer !== 2 || blockers.activationReady) throw new Error(`E3 post-apply blockers differ: ${JSON.stringify(blockers)}.`);
  const secondApply = await applyDibaPolicyRehearsal({ databasePath: target, realDatabasePath: config.databasePath, overrides }); const realAfterSecond = assertRealHash(config, 'after second apply'); const geographySecond = { mutations: secondApply.geography.filter(({ outcome }) => outcome === 'MUTATED_APPROVED_GEOGRAPHY').length, noops: secondApply.geography.filter(({ outcome }) => outcome === 'NOOP_EXISTING_GEOGRAPHY').length }; if (secondApply.finalRelinks.length || secondApply.inactivatedOrphans.length || geographySecond.mutations || geographySecond.noops !== 19) throw new Error('E3 second apply is not structurally idempotent.');
  const secondState = await policyState(target, overrides); const secondTransition = validateExpectedSameFeedTransition({ preState: rehearsalState, postState: secondState, bubbleSources: pre.bubbleBike.sources }); const secondBlockers = remaining(secondState.policy); if (!equal(blockers, secondBlockers) || secondBlockers.confirmed || secondBlockers.possible || secondBlockers.sessionDefer !== 2 || secondBlockers.activationReady) throw new Error(`E3 second apply changed the post blocker state: ${JSON.stringify(secondBlockers)}.`); if (!equal(sameFeedTransition.postSameFeed.map(({ signature }) => signature).sort(), secondTransition.postSameFeed.map(({ signature }) => signature).sort())) throw new Error('E3 second apply changed the post same-feed blocker set.');
  const bubbleRelinks = firstApply.finalRelinks.filter(({ source }) => ['escenari112430068591411746191364560', 'escenari112430068591411746191364562'].includes(source.sourceRecordId)); if (bubbleRelinks.length !== 2 || new Set(bubbleRelinks.map(({ afterPlanId }) => afterPlanId)).size !== 1) throw new Error('E3 BubbleBike did not reach one common target after apply.');
  const output = { generatedAt: new Date().toISOString(), rehearsalPath: target, rehearsalPreSha, copy, realHashes: { beforeCopy: realBefore, afterFirstApply: realAfterFirst, afterRepeatPreservation: realAfterRepeat, afterSecondApply: realAfterSecond, final: assertRealHash(config, 'final') }, preApply: { overrideCount: overrides.decisions.length, alreadySatisfiedConfirmed: pre.previous.length, pendingPossibleComponents: 22, pendingPossibleMappings: pre.mappings.length, validations: pre.validations, geography: { mutations: 0, noops: pre.geography.length }, blockers: pre.unresolved }, first: { finalRelinks: firstApply.finalRelinks, unexpectedRelinks, missingRelinks, planSources: { before: beforeSources, after: afterSources }, distinctOriginPlans: new Set(firstApply.finalRelinks.map(({ beforePlanId }) => beforePlanId)).size, distinctPublicTargets: new Set(firstApply.finalRelinks.map(({ afterPlanId }) => afterPlanId)).size, recomputedOrphans: firstApply.candidateOrphanPlanIds, inactivatedOrphans: firstApply.inactivatedOrphans, orphanChecks, geography: geographyFirst, invariantResults: firstApply.invariantResults }, publicProtection: { targetPlansCompared: pre.targetPlanIds.length, differences }, bubbleBike: { ...pre.bubbleBike, postCanonicalSchedule: bubbleSchedule, finalRelinks: bubbleRelinks }, sameFeedTransition, priorConfirmed: { changedMappings: confirmedChanged }, repeat: { possible: repeatPossible, confirmed: repeatConfirmed }, second: { finalRelinks: secondApply.finalRelinks, inactivatedOrphans: secondApply.inactivatedOrphans, geography: geographySecond, invariantResults: secondApply.invariantResults, sameFeedTransition: secondTransition }, blockers, databaseInvariants: { pre: { ...preCounts, integrity: integrityAt(target) }, post: { ...postCounts, integrity: integrityAt(target) } } };
  output.second.blockers = secondBlockers;
  const reports = path.join(root, 'data', 'reports'); await mkdir(reports, { recursive: true }); await writeFile(path.join(reports, 'diba-e3-possible-rehearsal.json'), `${JSON.stringify(output, null, 2)}\n`, 'utf8'); await writeFile(path.join(reports, 'diba-e3-possible-rehearsal.md'), `${render(output)}${renderSameFeedTransition(output)}`, 'utf8'); console.log(`DIBA E3 POSSIBLE reviewed-link rehearsal passed on: ${target}`); return output;
}
if (process.argv[1] === fileURLToPath(import.meta.url)) main().catch((error) => { console.error(`DIBA E3 POSSIBLE reviewed-link rehearsal failed: ${error.message}`); process.exitCode = 1; });
