import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import 'dotenv/config';
import { loadConfig } from '../backend/src/config.js';
import { openDatabase } from '../backend/src/db/database.js';
import { runDibaQualityAudit } from '../backend/src/diba/dibaQualityAudit.js';
import { E4_BASELINE_SHA, E4_CONFIRMATION, assertE4WritableBaseline } from '../backend/src/diba/dibaPolicyE4PrimaryLocal.js';
import { applyDibaPolicyE4PrimaryLocal, sha256File, verifyDibaRepeatPreservation } from '../backend/src/diba/dibaPolicyExecutor.js';
import { approvedPossibleSourceKeys } from '../backend/src/diba/dibaHumanReviewedPossible.js';
import { identityKey, loadDibaPolicyOverrides } from '../backend/src/diba/dibaPolicyOverrides.js';
import { loadPolicyIdentityIndex, planDibaPolicy } from '../backend/src/diba/dibaPolicyPlanner.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const overridePath = path.join(root, 'data-policy', 'diba-link-overrides.json');
const protectedFields = ['original_title', 'original_description', 'start_date', 'end_date', 'schedule_text', 'venue_name', 'address', 'latitude', 'longitude', 'website_url', 'image_url', 'ticket_url', 'status', 'inactive_at', 'featured', 'quality_score'];
const bubbleIds = ['escenari112430068591411746191364560', 'escenari112430068591411746191364562'];
function stamp() { return new Date().toISOString().replace(/[:.]/g, '-'); }
function key(value) { return identityKey(value); }
function equal(left, right) { return JSON.stringify(left) === JSON.stringify(right); }
function parseArguments(argv) { const values = {}; for (let index = 0; index < argv.length; index += 1) { const option = argv[index]; if (['--expected-sha', '--confirm'].includes(option) && argv[index + 1]) values[option === '--expected-sha' ? 'expectedSha' : 'confirmation'] = argv[++index]; else throw new Error(`Unknown or incomplete E4 argument: ${option}`); } return values; }
function counts(db) { return { plans: db.prepare('SELECT COUNT(*) AS count FROM plans').get().count, planSources: db.prepare('SELECT COUNT(*) AS count FROM plan_sources').get().count, categories: db.prepare('SELECT COUNT(*) AS count FROM plan_categories').get().count, occurrences: db.prepare('SELECT COUNT(*) AS count FROM plan_occurrences').get().count, sources: db.prepare('SELECT COUNT(*) AS count FROM sources').get().count, dibaSourceRecords: db.prepare("SELECT COUNT(*) AS count FROM plan_sources ps JOIN sources s ON s.id=ps.source_id WHERE s.key LIKE 'diba-%'").get().count, duplicateStableIdentities: db.prepare('SELECT COUNT(*) AS count FROM (SELECT source_id, source_record_id FROM plan_sources GROUP BY source_id, source_record_id HAVING COUNT(*) > 1)').get().count }; }
function snapshot(databasePath, targetIds) { const db = openDatabase(databasePath, { readonly: true }); try { const identities = db.prepare('SELECT s.key AS sourceKey, ps.source_record_id AS sourceRecordId, ps.plan_id AS planId FROM plan_sources ps JOIN sources s ON s.id=ps.source_id ORDER BY s.key, ps.source_record_id').all(); const plan = db.prepare('SELECT * FROM plans WHERE id=?'); const categories = db.prepare('SELECT category_id FROM plan_categories WHERE plan_id=? ORDER BY category_id'); const sources = db.prepare("SELECT key, enabled, allows_images FROM sources WHERE key LIKE 'diba-%' ORDER BY key").all(); return { identities, counts: counts(db), sources, integrity: db.pragma('integrity_check', { simple: true }), targets: Object.fromEntries(targetIds.map((id) => [id, { fields: Object.fromEntries(protectedFields.map((field) => [field, plan.get(id)?.[field]])), categories: categories.all(id).map(({ category_id: categoryId }) => categoryId) }])), plans: db.prepare('SELECT id, status FROM plans').all() }; } finally { db.close(); } }
function mappingDiff(before, after) { const map = (items) => new Map(items.map((item) => [`${item.sourceKey}:${item.sourceRecordId}`, item])); const left = map(before); const right = map(after); return { changed: [...left].filter(([item, value]) => right.has(item) && right.get(item).planId !== value.planId).map(([item, value]) => ({ key: item, beforePlanId: value.planId, afterPlanId: right.get(item).planId })), added: [...right].filter(([item]) => !left.has(item)).map(([item]) => item), removed: [...left].filter(([item]) => !right.has(item)).map(([item]) => item) }; }
function differences(before, after) { const output = []; for (const [id, left] of Object.entries(before)) { const right = after[id]; for (const field of protectedFields) if (left.fields[field] !== right.fields[field]) output.push({ planId: Number(id), field, before: left.fields[field], after: right.fields[field] }); if (!equal(left.categories, right.categories)) output.push({ planId: Number(id), field: 'categories' }); } return output; }
function members(item) { return item.cluster.records.map(({ sourceKey, sourceRecordId }) => `${sourceKey || item.cluster.sourceKey}:${sourceRecordId}`).sort(); }
function blockers(state, decision) { return state.policy.sameFeed.filter((item) => item.decision === decision).map((item) => ({ signature: members(item).join('|'), members: members(item), planIds: [...(item.planIds || item.cluster.planIds)].sort((a, b) => a - b) })); }
function validateTransition(pre, post, bubbleSources) { const before = blockers(pre, 'NEEDS_HUMAN_REVIEW'); const after = blockers(post, 'NEEDS_HUMAN_REVIEW'); const preSession = blockers(pre, 'KEEP_SEPARATE_SESSION'); const postSession = blockers(post, 'KEEP_SEPARATE_SESSION'); const signature = bubbleSources.map(key).sort().join('|'); const beforeSet = new Set(before.map(({ signature: item }) => item)); const afterSet = new Set(after.map(({ signature: item }) => item)); const removed = before.filter(({ signature: item }) => !afterSet.has(item)); const added = after.filter(({ signature: item }) => !beforeSet.has(item)); const consolidated = post.audit.sameFeed.clusters.find((cluster) => cluster.records.map(({ sourceKey = cluster.sourceKey, sourceRecordId }) => `${sourceKey}:${sourceRecordId}`).sort().join('|') === signature); if (!beforeSet.has(signature) || removed.length !== 1 || removed[0].signature !== signature || added.length || afterSet.has(signature) || !consolidated || new Set(consolidated.planIds).size !== 1) throw new Error('E4 same-feed transition is not exactly the approved BubbleBike removal.'); if (!equal(preSession.map(({ signature: item }) => item).sort(), postSession.map(({ signature: item }) => item).sort())) throw new Error('E4 session-DEFER stable components changed.'); return { preSameFeed: before, removed, postSameFeed: after, added, preSessionDefer: preSession, postSessionDefer: postSession, bubblePostCluster: { members: members({ cluster: consolidated }), planIds: consolidated.planIds } }; }
async function policyState(databasePath, overrides) { const audit = await runDibaQualityAudit({ databasePath }); const db = openDatabase(databasePath, { readonly: true }); try { const index = loadPolicyIdentityIndex(db); const policy = planDibaPolicy({ auditReport: audit, overrides, identityIndex: index }); return { audit, index, policy, remaining: { confirmed: policy.crossSource.confirmed.filter(({ activationBlocker }) => activationBlocker).length, possible: policy.crossSource.possible.filter(({ activationBlocker }) => activationBlocker).length, sameFeed: policy.sameFeed.filter(({ decision }) => decision === 'NEEDS_HUMAN_REVIEW').length, sessionDefer: policy.sameFeed.filter(({ decision }) => decision === 'KEEP_SEPARATE_SESSION').length, activationReady: policy.activation.publicActivationReady } }; } finally { db.close(); } }
function list(components) { return components.length ? components.map(({ members: values }) => `- ${values.join(', ')}`).join('\n') : '- none'; }
function markdown(report) { return `# DIBA M1.4E4 — real local POSSIBLE-link apply\n\n**REAL LOCAL DATABASE MUTATED ONLY BY AUTHORIZED E4 TRANSACTION. DIBA REMAINS DISABLED.**\n\n## AUTHORIZATION\n\n- Canonical path: \`${report.authorization.canonicalPath}\`\n- Baseline / PRE SHA: \`${report.hashes.pre}\`\n- Result: ${report.authorization.result}; consumed: ${report.authorization.consumed}\n\n## BACKUP\n\n- \`${report.backup.path}\`\n- SHA: \`${report.backup.sha256}\`; integrity: ${report.backup.integrity}; equivalent: ${report.backup.logicalEquivalent}\n\n## APPLY\n\n- 23 approved mappings: ${report.apply.changedMappings.length}; unexpected ${report.apply.unexpectedRelinks.length}; missing ${report.apply.missingRelinks.length}\n- plan_sources: ${report.apply.planSources.before} → ${report.apply.planSources.after}\n- Components: 21 x 1→1 and BubbleBike 2→1\n- Orphans: ${report.orphans.distinctOrigins} origins / ${report.orphans.recomputed.length} source-less / ${report.orphans.inactivated.length} inactivated\n- Protected canonical differences: ${report.canonical.differences.length}\n- BubbleBike schedule: ${report.bubbleBike.preSchedule} → ${report.bubbleBike.postSchedule}\n\n## SAME-FEED TRANSITION\n\nPRE:\n${list(report.sameFeed.preSameFeed)}\n\nRemoved (BubbleBike only):\n${list(report.sameFeed.removed)}\n\nPOST:\n${list(report.sameFeed.postSameFeed)}\n\nAdded:\n${list(report.sameFeed.added)}\n\nBubbleBike is removed solely because the approved human 2→1 cross-source consolidation leaves both DIBA identities on one public plan. It is not an automatic same-feed decision.\n\n## SESSION-DEFER\n\nPRE:\n${list(report.sameFeed.preSessionDefer)}\n\nPOST:\n${list(report.sameFeed.postSessionDefer)}\n\n## POST\n\n- Geography: ${report.geography.mutations} mutations / ${report.geography.noops} NOOP\n- Blockers: CONFIRMED ${report.post.blockers.confirmed}; POSSIBLE ${report.post.blockers.possible}; same-feed ${report.post.blockers.sameFeed}; session-DEFER ${report.post.blockers.sessionDefer}; activation=${report.post.blockers.activationReady}\n- Repeat preservation: POSSIBLE ${report.repeat.possible.verified.length}/23; CONFIRMED ${report.repeat.confirmed.verified.length}/11\n- POST SHA: \`${report.hashes.post}\`\n`; }
export async function main(argv = process.argv.slice(2), config = loadConfig()) {
  const args = parseArguments(argv); const overrides = await loadDibaPolicyOverrides(overridePath); const backupPath = path.join(root, 'data', 'backups', `quefem_before_diba_m1_4e4_${stamp()}.sqlite`); const result = await applyDibaPolicyE4PrimaryLocal({ args, config, overrides, backupPath }); const targetIds = result.pre.prepared.scope.targetPlanIds; const before = snapshot(result.backup.path, targetIds); const after = snapshot(config.databasePath, targetIds); const diff = mappingDiff(before.identities, after.identities); const approved = approvedPossibleSourceKeys(); const changed = new Set(diff.changed.map(({ key: item }) => item)); const unexpectedRelinks = diff.changed.filter(({ key: item }) => !approved.has(item)); const missingRelinks = [...approved].filter((item) => !changed.has(item));
  if (diff.changed.length !== 23 || diff.added.length || diff.removed.length || unexpectedRelinks.length || missingRelinks.length) throw new Error('E4 independent SQLite relink validation did not find exactly the 23 approved POSSIBLE sources.'); if (!equal(before.counts, after.counts) || !equal(before.sources, after.sources) || after.integrity !== 'ok' || after.counts.duplicateStableIdentities) throw new Error('E4 database-wide cardinality/source/integrity validation failed.'); const canonicalDifferences = differences(before.targets, after.targets); if (canonicalDifferences.length) throw new Error('E4 changed protected public canonical fields.');
  const pre = await policyState(result.backup.path, overrides); const post = await policyState(config.databasePath, overrides); const transition = validateTransition(pre, post, result.pre.prepared.scope.bubbleBike.sources); if (post.remaining.confirmed || post.remaining.possible || post.remaining.sameFeed !== 3 || post.remaining.sessionDefer !== 2 || post.remaining.activationReady || post.policy.mutationPlan.phases.finalSourceMappings.length || post.policy.mutationPlan.phases.recomputeOrphans.originalAffectedDibaStagingPlans.length || post.policy.mutationPlan.phases.explicitGeography.length !== 19) throw new Error('E4 post-apply readonly policy state differs.');
  const mapPlan = new Map(after.identities.map((value) => [`${value.sourceKey}:${value.sourceRecordId}`, value.planId])); const bubbleRelinks = result.apply.finalRelinks.filter(({ source }) => bubbleIds.includes(source.sourceRecordId)); if (bubbleRelinks.length !== 2 || new Set(bubbleRelinks.map(({ afterPlanId }) => afterPlanId)).size !== 1 || bubbleRelinks.some(({ finalTargetAnchor }) => key(finalTargetAnchor) !== 'gencat-agenda:2026071400044@f3789cc34f003307')) throw new Error('E4 BubbleBike did not reach its exact common public target.'); const postSchedule = after.targets[bubbleRelinks[0].afterPlanId]?.fields.schedule_text; if (postSchedule !== result.pre.prepared.scope.bubbleBike.canonicalSchedule) throw new Error('E4 changed BubbleBike combined public schedule.');
  const originIds = result.apply.candidateOrphanPlanIds; const postDb = openDatabase(config.databasePath, { readonly: true }); let orphanChecks; try { orphanChecks = result.apply.inactivatedOrphans.map(({ planId }) => ({ planId, planSources: postDb.prepare('SELECT COUNT(*) AS count FROM plan_sources WHERE plan_id=?').get(planId).count, enabledProvenance: postDb.prepare('SELECT COUNT(*) AS count FROM plan_sources ps JOIN sources s ON s.id=ps.source_id WHERE ps.plan_id=? AND s.enabled=1').get(planId).count, status: postDb.prepare('SELECT status FROM plans WHERE id=?').get(planId).status })); } finally { postDb.close(); } if (orphanChecks.some(({ planSources, enabledProvenance, status }) => planSources || enabledProvenance || status !== 'inactive')) throw new Error('E4 unsafe orphan inactivation detected.');
  const confirmedRelinks = result.pre.prepared.scope.confirmedValidations.map(({ source, planId }) => ({ source, afterPlanId: planId })); const repeat = { possible: verifyDibaRepeatPreservation({ databasePath: config.databasePath, relinks: result.apply.finalRelinks }), confirmed: verifyDibaRepeatPreservation({ databasePath: config.databasePath, relinks: confirmedRelinks }) }; if (repeat.possible.verified.length !== 23 || repeat.confirmed.verified.length !== 11) throw new Error('E4 repeat preservation failed.'); const geography = { mutations: result.apply.geography.filter(({ outcome }) => outcome === 'MUTATED_APPROVED_GEOGRAPHY').length, noops: result.apply.geography.filter(({ outcome }) => outcome !== 'MUTATED_APPROVED_GEOGRAPHY').length }; if (geography.mutations || geography.noops !== 19) throw new Error('E4 geography mutation scope differs.'); let consumed = false; try { assertE4WritableBaseline({ databasePath: config.databasePath, args, config }); } catch (error) { consumed = /expected SHA does not match/.test(error.message); } if (!consumed || sha256File(config.databasePath) === E4_BASELINE_SHA) throw new Error('E4 authorization was not consumed.');
  const report = { generatedAt: new Date().toISOString(), authorization: { canonicalPath: result.pre.primary, baseline: E4_BASELINE_SHA, preSha: result.pre.sha256, result: 'AUTHORIZED', consumed }, hashes: { pre: result.pre.sha256, backup: result.backup.sha256, post: result.postSha256, final: sha256File(config.databasePath) }, backup: result.backup, preview: { overrideCount: overrides.decisions.length, satisfiedConfirmed: result.pre.prepared.scope.confirmedValidations.length, reviewedPossibleComponents: result.pre.prepared.scope.reviewedPossible, pendingMappings: result.pre.prepared.scope.mappings, blockers: result.pre.prepared.scope.unresolved, geography: result.pre.prepared.scope.geography }, apply: { changedMappings: diff.changed, unexpectedRelinks, missingRelinks, addedIdentities: diff.added, removedIdentities: diff.removed, planSources: { before: before.counts.planSources, after: after.counts.planSources }, targetPlans: [...new Set(result.apply.finalRelinks.map(({ afterPlanId }) => afterPlanId))] }, bubbleBike: { sources: result.pre.prepared.scope.bubbleBike.sources, target: result.pre.prepared.scope.bubbleBike.target, preSchedule: result.pre.prepared.scope.bubbleBike.canonicalSchedule, postSchedule, relinks: bubbleRelinks }, orphans: { distinctOrigins: new Set(originIds).size, recomputed: originIds, inactivated: result.apply.inactivatedOrphans, checks: orphanChecks }, canonical: { targetsCompared: targetIds.length, differences: canonicalDifferences }, priorConfirmed: { changedMappings: [], count: confirmedRelinks.length }, sameFeed: transition, geography, invariants: { before: before.counts, after: after.counts, integrity: after.integrity, dibaSourcesUnchanged: equal(before.sources, after.sources) }, post: { pendingAutomaticRelinks: 0, pendingReviewedRelinks: post.policy.mutationPlan.phases.finalSourceMappings.length, pendingOrphans: post.policy.mutationPlan.phases.recomputeOrphans.originalAffectedDibaStagingPlans.length, blockers: post.remaining }, repeat };
  const reports = path.join(root, 'data', 'reports'); await mkdir(reports, { recursive: true }); await writeFile(path.join(reports, 'diba-e4-possible-real-local-apply.json'), `${JSON.stringify(report, null, 2)}\n`, 'utf8'); await writeFile(path.join(reports, 'diba-e4-possible-real-local-apply.md'), markdown(report)); console.log(`DIBA E4 real local POSSIBLE-link apply passed: ${config.databasePath}`); return report;
}
if (process.argv[1] === fileURLToPath(import.meta.url)) main().catch((error) => { console.error(`DIBA E4 real local POSSIBLE-link apply failed: ${error.message}`); process.exitCode = 1; });
