import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import 'dotenv/config';
import { loadConfig } from '../backend/src/config.js';
import { openDatabase } from '../backend/src/db/database.js';
import { runDibaQualityAudit } from '../backend/src/diba/dibaQualityAudit.js';
import { appendApprovedPossibleOverrides, summarizeReviewedPossiblePolicy, validateE2Prewrite } from '../backend/src/diba/dibaHumanReviewedPossible.js';
import { identityKey, validateDibaPolicyOverrides } from '../backend/src/diba/dibaPolicyOverrides.js';
import { loadPolicyIdentityIndex, planDibaPolicy } from '../backend/src/diba/dibaPolicyPlanner.js';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const overridePath = path.join(projectRoot, 'data-policy', 'diba-link-overrides.json'); const reportDirectory = path.join(projectRoot, 'data', 'reports');
function payloads(db) { return new Map(db.prepare(`SELECT s.key AS sourceKey, ps.source_record_id AS sourceRecordId, ps.source_payload_json AS payload FROM plan_sources ps JOIN sources s ON s.id=ps.source_id WHERE s.key LIKE 'diba-%'`).all().map(({ sourceKey, sourceRecordId, payload }) => [`${sourceKey}:${sourceRecordId}`, JSON.parse(payload || '{}')])); }
function markdown(output) {
  const rows = output.validation.map((item) => `| ${item.source.sourceKey}:${item.source.sourceRecordId} | ${item.target.sourceKey}:${item.target.sourceRecordId} | ${item.componentId} | ${item.sourcePlanIdDiagnostic} | ${item.targetPlanIdDiagnostic} | PASS |`).join('\n');
  return `# DIBA M1.4E2 — Human-reviewed POSSIBLE links dry-run\n\n**POSSIBLE HUMAN DECISIONS RECORDED — NO SQLITE MUTATION PERFORMED.**\n\nOverride decisions: ${output.overrideState.previousCount} previous + ${output.overrideState.addedCount} approved POSSIBLE = ${output.overrideState.totalCount}.\n\n## Exact reviewed mappings\n\n| DIBA source | Public target | POSSIBLE component | Origin plan (diagnostic) | Target plan (diagnostic) | Validation |\n| --- | --- | --- | --- | --- | --- |\n${rows}\n\n## Component safety\n\nReviewed POSSIBLE components: ${output.summary.reviewedPossibleComponents}; reviewed source mappings: ${output.summary.reviewedPossibleSourceMappings}; unexpected mappings: ${output.summary.unexpectedMappings.length}.\n\nBubbleBike sources: ${output.bubbleBike.sources.map(({ sourceKey, sourceRecordId }) => `${sourceKey}:${sourceRecordId}`).join(', ')} -> ${output.bubbleBike.target.sourceKey}:${output.bubbleBike.target.sourceRecordId}. Sessions: ${output.bubbleBike.sessionStarts.join(', ')}. Its Gencat canonical schedule remains protected as **KEEP_EXISTING**.\n\n## Orphan preview\n\nDistinct DIBA origin plans: ${output.summary.distinctOriginDibaPlans}; predicted future zero-provenance DIBA staging plans: ${output.summary.expectedFutureOrphans.length}; every predicted orphan DIBA-only: ${output.summary.everyExpectedOrphanIsDibaStaging}.\n\n## Remaining blockers\n\nCONFIRMED ${output.summary.remaining.confirmed}; POSSIBLE ${output.summary.remaining.possible}; same-feed ${output.summary.remaining.sameFeed}; session DEFER ${output.summary.remaining.sessionDefer}. Geography preview: ${output.summary.geography.plannedMutations} planned NOOP-compatible operations across ${output.summary.geography.total} records. **PUBLIC ACTIVATION READY: ${output.summary.publicActivationReady ? 'YES' : 'NO'}**.\n`;
}

export async function main({ databasePath = loadConfig().databasePath } = {}) {
  const before = JSON.parse(await readFile(overridePath, 'utf8')); validateDibaPolicyOverrides(before); const audit = await runDibaQualityAudit({ databasePath }); const db = openDatabase(databasePath, { readonly: true }); let index; let preflight;
  try { index = loadPolicyIdentityIndex(db); const policy = planDibaPolicy({ auditReport: audit, overrides: before, identityIndex: index }); preflight = validateE2Prewrite({ existingOverrides: before, policy, identityIndex: index, sourcePayloadByIdentity: payloads(db) }); } finally { db.close(); }
  const after = appendApprovedPossibleOverrides(before); await writeFile(overridePath, `${JSON.stringify(after, null, 2)}\n`, 'utf8');
  const postAudit = await runDibaQualityAudit({ databasePath }); const postDb = openDatabase(databasePath, { readonly: true }); let postPolicy; let summary;
  try { const postIndex = loadPolicyIdentityIndex(postDb); postPolicy = planDibaPolicy({ auditReport: postAudit, overrides: after, identityIndex: postIndex }); summary = summarizeReviewedPossiblePolicy({ policy: postPolicy, identityIndex: postIndex }); } finally { postDb.close(); }
  const validation = preflight.validation.map((item) => ({ ...item, plannedExactly: summary.newMappings.some(({ source, finalTargetAnchor }) => identityKey(source) === identityKey(item.source) && identityKey(finalTargetAnchor) === identityKey(item.target)) })); if (validation.some(({ plannedExactly }) => !plannedExactly)) throw new Error('E2 planner did not produce every approved mapping exactly.');
  const output = { generatedAt: new Date().toISOString(), databasePath: path.resolve(databasePath), readOnlyDryRun: true, humanDecisionsRecorded: true, noSqliteMutationPerformed: true, overrideState: { previousCount: preflight.existingCount, addedCount: preflight.approvedCount, totalCount: after.decisions.length }, validation, summary, bubbleBike: preflight.bubbleBike, fieldOwnership: { keepExisting: ['title', 'description', 'start_date', 'end_date', 'venue', 'address', 'coordinates', 'url'], neverFromDiba: ['categories', 'image', 'status', 'ranking/featured', 'commerce/affiliate'] } };
  await mkdir(reportDirectory, { recursive: true }); const jsonPath = path.join(reportDirectory, 'diba-human-reviewed-possible-dry-run.json'); const markdownPath = path.join(reportDirectory, 'diba-human-reviewed-possible-dry-run.md'); await writeFile(jsonPath, `${JSON.stringify(output, null, 2)}\n`, 'utf8'); await writeFile(markdownPath, markdown(output), 'utf8');
  console.log(`DIBA human-reviewed POSSIBLE dry-run written read-only: ${markdownPath}`); console.log(`DIBA human-reviewed POSSIBLE JSON: ${jsonPath}`); return { jsonPath, markdownPath, output };
}
if (process.argv[1] === fileURLToPath(import.meta.url)) main().catch((error) => { console.error(`DIBA human-reviewed POSSIBLE dry-run failed: ${error.message}`); process.exitCode = 1; });
